on: push
name: Publish Master
jobs:
  build-and-publish-operator:
    name: Build and Publish humio-ingest-load-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version information
      run: |
        echo "GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
        echo "RELEASE_COMMIT=$(git rev-parse --verify HEAD)" >> $GITHUB_ENV
        echo "RELEASE_DATE=$(date --iso-8601=seconds)" >> $GITHUB_ENV
    - name: docker build
      run: docker build . -t humio/humio-ingest-load-test:${{ env.GIT_SHA }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install six
    - name: CrowdStrike Container Image Scan Humio Ingest Load Test
      uses: crowdstrike/container-image-scan-action@v1
      with:
        falcon_client_id: 1cd30708cb31442f85a6eec83279fe7b
        container_repository: humio/humio-ingest-load-test
        container_tag: ${{ env.GIT_SHA }}
        retry_count: 60
      env:
        FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run:  docker push humio/humio-ingest-load-test:${{ env.GIT_SHA}}
